#!/bin/bash

# =============================================================================
# Seed local A2A payments (+ reconciliation PR rows) — 1:1 with live shape
# =============================================================================
# Populates `calytics-a2a-local-payments` with ~26 fixture rows spanning every
# (status × session_status × payment_tracking_enabled × reconciliation_status)
# combination operational tooling renders, AND — for every tracked payment —
# a matching `calytics-shared-local-reconcilable-transactions` (PR) row with the
# exact production item shape (mandate_id PK = clientId#tenantId#paymentId,
# sk = TRANSACTION#paymentId, additional_information.{endToEndId,senderIban,
# instant,purpose}, match_metadata for reconciled rows).
#
# Drives the calytics-fe /a2a/payment table: the reconciliation dot column shows
# green (Reconciled) / blue (Pending) / amber (AmbiguousMatch) / red (Unmatchable)
# for tracked rows, grey (Not tracked) for successful-but-untracked, faint for N/A.
#
# Idempotent: every payment_id is `seed-a2a-*`; we delete-then-put both tables.
#
# Usage:   cal seed a2a-payments
# Env:     AWS_ENDPOINT_URL, AWS_REGION, PAYMENTS_TABLE_NAME,
#          RECONCILABLE_TRANSACTIONS_TABLE_NAME, SEED_A2A_CLIENT_ID
# =============================================================================

set -euo pipefail

export AWS_ENDPOINT_URL="${AWS_ENDPOINT_URL:-http://localhost:4566}"
export AWS_REGION="${AWS_REGION:-eu-central-1}"
export AWS_PAGER=""

PAYMENTS_TABLE="${PAYMENTS_TABLE_NAME:-calytics-a2a-local-payments}"
PR_TABLE="${RECONCILABLE_TRANSACTIONS_TABLE_NAME:-calytics-shared-local-reconcilable-transactions}"
# Base payment-transactions table: the be-admin /payment/transactions endpoint reads THIS table and
# joins the PR (reconcilable) row onto each base row. The FE /a2a/payment reconciliation dot column
# is driven by that join, so every tracked payment needs a matching base row here too.
PT_TABLE="${PAYMENT_TRANSACTIONS_TABLE_NAME:-calytics-a2a-payment-transactions}"
# Match-conflicts table (DEC-062): when the matcher DEFERS an ambiguous same-(amount,currency) group it
# writes an over-complete conflict record (every payment + every contested credit + the full per-pair
# condition matrix) so a human or LLM agent can reverse-engineer the decision. We seed one for the 008/009
# shared-family-IBAN pair so the table is exercised 1:1 with live.
CONFLICTS_TABLE="${MATCH_CONFLICTS_TABLE_NAME:-payment-reconciliation-local-match-conflicts}"
# Resolve the client these fixtures attach to. The FE /a2a/payment table is
# filtered by the logged-in client's id, so the fixtures MUST belong to the real
# locally-seeded main client — whose id is a random uuid generated by be-admin's
# seed:clients (CPM refactor, Jun 2026), no longer the historical pinned uuid.
# Resolve it from Postgres (the same users -> user_clients join be-admin uses),
# honouring an explicit SEED_A2A_CLIENT_ID override, and fall back to the historical
# fixture uuid only when Postgres is unreachable (pure-DynamoDB standalone usage).
SEED_A2A_CLIENT_EMAIL="${SEED_A2A_CLIENT_EMAIL:-main.client@gmail.com}"
POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_USER="${POSTGRES_USER:-postgres}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-register}"
POSTGRES_DB="${POSTGRES_DB:-calytics-admin}"
FALLBACK_CLIENT_ID="9f8a1f8c-56fd-43f9-b0dd-db0c86cf424a"

resolve_a2a_client_id() {
    command -v psql >/dev/null 2>&1 || return 0
    PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -t -A -q \
        -c "SELECT uc.client_id FROM user_clients uc JOIN users u ON u.user_id = uc.user_id WHERE u.email = '$SEED_A2A_CLIENT_EMAIL' LIMIT 1;" 2>/dev/null | grep -v '^$' | head -1 || true
}

if [ -n "${SEED_A2A_CLIENT_ID:-}" ]; then
    CLIENT_ID="$SEED_A2A_CLIENT_ID"
else
    CLIENT_ID="$(resolve_a2a_client_id)"
    [ -z "$CLIENT_ID" ] && CLIENT_ID="$FALLBACK_CLIENT_ID"
fi

GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; NC='\033[0m'
print_info()    { echo -e "${CYAN}ℹ${NC}  $1"; }
print_success() { echo -e "${GREEN}✓${NC}  $1"; }
print_warn()    { echo -e "${YELLOW}!${NC}  $1"; }

ddb() { aws --endpoint-url "$AWS_ENDPOINT_URL" --region "$AWS_REGION" dynamodb "$@"; }

ddb describe-table --table-name "$PAYMENTS_TABLE" >/dev/null 2>&1 || { print_warn "Table $PAYMENTS_TABLE not found — run 'cal seed a2a-tables' first."; exit 1; }
PR_AVAILABLE=true
ddb describe-table --table-name "$PR_TABLE" >/dev/null 2>&1 || { print_warn "PR table $PR_TABLE not found — PR rows will be skipped."; PR_AVAILABLE=false; }
PT_AVAILABLE=true
ddb describe-table --table-name "$PT_TABLE" >/dev/null 2>&1 || { print_warn "Base payment-transactions table $PT_TABLE not found — FE reconciliation join rows will be skipped."; PT_AVAILABLE=false; }
CONFLICTS_AVAILABLE=true
ddb describe-table --table-name "$CONFLICTS_TABLE" >/dev/null 2>&1 || { print_warn "Match-conflicts table $CONFLICTS_TABLE not found — conflict row will be skipped."; CONFLICTS_AVAILABLE=false; }

NOW_MS="$(($(date +%s) * 1000))"; HOUR_MS=$((60 * 60 * 1000)); DAY_MS=$((24 * HOUR_MS))
declare -A T=(
  [now]="$NOW_MS" [5min]=$((NOW_MS - 5*60*1000)) [30min]=$((NOW_MS - 30*60*1000))
  [2h]=$((NOW_MS - 2*HOUR_MS)) [6h]=$((NOW_MS - 6*HOUR_MS)) [12h]=$((NOW_MS - 12*HOUR_MS))
  [1d]=$((NOW_MS - DAY_MS)) [2d]=$((NOW_MS - 2*DAY_MS)) [3d]=$((NOW_MS - 3*DAY_MS)) [5d]=$((NOW_MS - 5*DAY_MS))
)

# IBANs reused so "same payer" / "shared family IBAN" scenarios exist.
IBAN_A="DE60500105175448413261"; IBAN_B="DE89370400440532013000"; IBAN_C="DE14100500001664735239"
IBAN_FAM="LT033500010016576309"   # shared family/account IBAN (Revolut-style)
MERCHANT="DE04720500000252868930"; MERCHANT_FOX="DE74100500000191445100"

# payment_id|tenant|status|session_status|amount|currency|finalized|wh|cb_sent|cb_deliv|created|sender_name|sender_iban|recipient_name|recipient_iban|purpose|correlation|e2e|instant|tracking|recon_status
ROWS=(
  # --- tracked + reconciled (green) ---
  "seed-a2a-001|tenant-demo|SUCCESSFUL|COMPLETED|42.50|EUR|true|true|true|true|6h|Alice Andersen|$IBAN_A|Calytics GmbH|$MERCHANT|Order 1001 coffee subscription|order-1001|e2e-order-1001|true|true|Reconciled"
  "seed-a2a-002|tenant-demo|SUCCESSFUL|COMPLETED|199.00|EUR|true|true|true|true|2h|Bob Brunner|$IBAN_B|Calytics GmbH|$MERCHANT|Invoice INV-2002 annual plan|order-1002|e2e-order-1002|true|true|Reconciled"
  "seed-a2a-003|tenant-premium|SUCCESSFUL|COMPLETED|9.99|EUR|true|true|true|true|30min|Hannah Huber|$IBAN_C|Calytics GmbH|$MERCHANT|Subscription month 5|sub-0509|e2e-sub-0509|true|true|Reconciled"
  "seed-a2a-004|tenant-demo|SUCCESSFUL|COMPLETED|1250.00|EUR|true|true|true|true|1d|Greta Graf|$IBAN_A|Calytics GmbH|$MERCHANT|Order 1010 hardware bundle|order-1010|e2e-order-1010|false|true|Reconciled"
  # --- tracked + pending (blue, awaiting bank credit) ---
  "seed-a2a-005|tenant-demo|SUCCESSFUL|COMPLETED|74.99|EUR|true|true|true|true|5min|Diana Diaz|$IBAN_C|Calytics GmbH|$MERCHANT|Order 1004 awaiting settlement|order-1004|e2e-order-1004|true|true|Pending"
  "seed-a2a-006|tenant-demo|SUCCESSFUL|COMPLETED|330.00|EUR|true|true|true|true|2h|Erik Eriksen|$IBAN_B|Calytics GmbH|$MERCHANT|Order 1005 standard sepa pending|order-1005|e2e-order-1005|false|true|Pending"
  "seed-a2a-007|tenant-premium|SUCCESSFUL|COMPLETED|25.00|EUR|true|true|true|true|12h|Ivan Ivanov|$IBAN_A|Calytics GmbH|$MERCHANT|Premium upgrade pending|sub-upg|e2e-sub-upg|true|true|Pending"
  # --- tracked + ambiguous (amber) — shared family IBAN, same amount, no e2e on credit ---
  "seed-a2a-008|tenant-fox|SUCCESSFUL|COMPLETED|2.07|EUR|true|true|true|true|2h|Max P|$IBAN_FAM|FOXPAY UG|$MERCHANT_FOX|Reconciliation test 6|||true|true|AmbiguousMatch"
  "seed-a2a-009|tenant-fox|SUCCESSFUL|COMPLETED|2.07|EUR|true|true|true|true|2h|Sister P|$IBAN_FAM|FOXPAY UG|$MERCHANT_FOX|Reconciliation test 6|||true|true|AmbiguousMatch"
  # --- tracked + unmatchable (red) — no credit found in window ---
  "seed-a2a-010|tenant-demo|SUCCESSFUL|COMPLETED|512.00|EUR|true|true|true|true|5d|Frieda Fischer|$IBAN_B|Calytics GmbH|$MERCHANT|Order 1007 no credit found|order-1007|e2e-order-1007|false|true|Unmatchable"
  # --- successful but NOT tracked (grey "Not tracked") ---
  "seed-a2a-011|tenant-demo|SUCCESSFUL|COMPLETED|15.00|EUR|true|true|true|true|6h|Cedric Albeke|$IBAN_A|Calytics GmbH|$MERCHANT|Order 1011 tracking off|order-1011||true|false|none"
  "seed-a2a-012|tenant-demo|SUCCESSFUL|COMPLETED|88.40|EUR|true|true|true|false|1d|Bob Brunner|$IBAN_B|Calytics GmbH|$MERCHANT|Order 1012 tracking off webhook stuck|order-1012||true|false|none"
  "seed-a2a-013|tenant-premium|SUCCESSFUL|COMPLETED|49.00|CHF|true|true|true|true|2d|Nadia Nowak|$IBAN_C|Calytics GmbH|$MERCHANT|Order 1013 CHF untracked|order-1013||true|false|none"
  # --- non-terminal / non-successful (N/A, faint dot) ---
  "seed-a2a-014|tenant-demo|OPEN|NOT_YET_OPENED|2.50|EUR|false|false|false|false|now|Cedric Albeke|$IBAN_A|FOXPAY UG|$MERCHANT_FOX|Premium key link sent|order-1014||true|false|none"
  "seed-a2a-015|tenant-demo|OPEN|IN_PROGRESS|120.00|EUR|false|false|false|false|5min|Diana Diaz|$IBAN_C|Calytics GmbH|$MERCHANT|Order 1015 on bank webform|order-1015||true|false|none"
  "seed-a2a-016|tenant-demo|PENDING|IN_PROGRESS|64.00|EUR|false|false|false|false|30min|Olaf Olsen|$IBAN_B|Calytics GmbH|$MERCHANT|Order 1016 instant pending at bank|order-1016||true|false|none"
  "seed-a2a-017|tenant-demo|NOT_SUCCESSFUL|COMPLETED_WITH_ERROR|330.00|EUR|true|true|true|true|1d|Erik Eriksen|$IBAN_B|Calytics GmbH|$MERCHANT|Order 1017 bank rejected|order-1017||true|false|none"
  "seed-a2a-018|tenant-demo|DISCARDED|ABORTED|18.00|EUR|true|true|true|true|2d|Frieda Fischer|$IBAN_A|Calytics GmbH|$MERCHANT|Order 1018 customer cancelled|order-1018||true|false|none"
  "seed-a2a-019|tenant-demo|DISCARDED|EXPIRED|1500.00|EUR|true|false|true|true|3d|Gunther Gross|$IBAN_B|Calytics GmbH|$MERCHANT|Order 1019 session expired|order-1019||false|false|none"
  "seed-a2a-020|tenant-fox|UNKNOWN|COMPLETED|3.50|EUR|true|true|true|false|2d|Petra Pohl|$IBAN_FAM|FOXPAY UG|$MERCHANT_FOX|Order 1020 outcome undetermined|order-1020||true|false|none"
  # --- more tracked variety (purpose-disambiguated, different currencies, instant/standard) ---
  "seed-a2a-021|tenant-demo|SUCCESSFUL|COMPLETED|7.77|EUR|true|true|true|true|6h|Quentin Quast|$IBAN_A|Calytics GmbH|$MERCHANT|Invoice INV-1001 monthly coffee beans|order-1021|e2e-1021|true|true|Reconciled"
  "seed-a2a-022|tenant-demo|SUCCESSFUL|COMPLETED|7.77|EUR|true|true|true|true|6h|Quentin Quast|$IBAN_A|Calytics GmbH|$MERCHANT|Invoice INV-2002 espresso cups|order-1022|e2e-1022|true|true|Reconciled"
  "seed-a2a-023|tenant-premium|SUCCESSFUL|COMPLETED|250.00|USD|true|true|true|true|12h|Rita Roth|$IBAN_C|Calytics GmbH|$MERCHANT|Order 1023 USD reconciled|order-1023|e2e-1023|true|true|Reconciled"
  "seed-a2a-024|tenant-premium|SUCCESSFUL|COMPLETED|410.00|EUR|true|true|true|true|1d|Sven Svensson|$IBAN_B|Calytics GmbH|$MERCHANT|Order 1024 standard sepa settled next day|order-1024|e2e-1024|false|true|Reconciled"
  "seed-a2a-025|tenant-premium|SUCCESSFUL|COMPLETED|33.00|EUR|true|true|true|true|2h|Tomas Toth|$IBAN_C|Calytics GmbH|$MERCHANT|Order 1025 instant pending|order-1025|e2e-1025|true|true|Pending"
  "seed-a2a-026|tenant-fox|SUCCESSFUL|COMPLETED|5.00|EUR|true|true|true|true|6h|Petra Pohl|$IBAN_FAM|FOXPAY UG|$MERCHANT_FOX|FoxPay express checkout reconciled|order-1026|e2e-1026|true|true|Reconciled"
)

print_info "Reseeding ${#ROWS[@]} A2A payments in $PAYMENTS_TABLE (client $CLIENT_ID) + PR rows in $PR_TABLE"

# ---------- idempotent delete (both tables) ----------
for row in "${ROWS[@]}"; do
  pid="$(echo "$row" | awk -F'|' '{print $1}')"; tenant="$(echo "$row" | awk -F'|' '{print $2}')"
  ddb delete-item --table-name "$PAYMENTS_TABLE" --key "{\"payment_id\":{\"S\":\"$pid\"}}" >/dev/null 2>&1 || true
  if [ "$PR_AVAILABLE" = true ]; then
    ddb delete-item --table-name "$PR_TABLE" \
      --key "{\"mandate_id\":{\"S\":\"$CLIENT_ID#$tenant#$pid\"},\"sk\":{\"S\":\"TRANSACTION#$pid\"}}" >/dev/null 2>&1 || true
  fi
  if [ "$PT_AVAILABLE" = true ]; then
    ddb delete-item --table-name "$PT_TABLE" \
      --key "{\"payment_id\":{\"S\":\"$pid\"},\"sk\":{\"S\":\"TRANSACTION#$pid\"}}" >/dev/null 2>&1 || true
  fi
done

esc() { printf '%s' "$1" | sed 's/"/\\"/g'; }

for row in "${ROWS[@]}"; do
  IFS='|' read -r pid tenant status session amount currency finalized wh cb_sent cb_deliv created_key sname siban rname riban purpose corr e2e instant tracking recon <<< "$row"
  created="${T[$created_key]}"; expires=$((created + 30*60*1000)); composite="$CLIENT_ID#$tenant"
  vsid="webform-$pid"; vurl="https://webform-sandbox.finapi.io/wf/$vsid"
  # optional fields
  e2e_attr=""; [ -n "$e2e" ] && e2e_attr=", \"end_to_end_id\": {\"S\": \"$(esc "$e2e")\"}"
  corr_attr=""; [ -n "$corr" ] && corr_attr="\"correlation_id\": {\"S\": \"$(esc "$corr")\"},"

  cat > /tmp/a2a-seed-item.json <<JSON
{
  "payment_id": {"S": "$pid"},
  "client_id": {"S": "$CLIENT_ID"},
  "tenant_id": {"S": "$tenant"},
  "tenant_composite_key": {"S": "$composite"},
  "amount": {"N": "$amount"},
  "currency": {"S": "$currency"},
  "status": {"S": "$status"},
  "session_status": {"S": "$session"},
  $corr_attr
  "purpose": {"S": "$(esc "$purpose")"},
  "sender": {"M": {"name": {"S": "$(esc "$sname")"}, "iban": {"S": "$siban"}}},
  "recipient": {"M": {"name": {"S": "$(esc "$rname")"}, "iban": {"S": "$riban"}}},
  "sender_iban": {"S": "$siban"},
  "recipient_iban": {"S": "$riban"},
  "vendor_name": {"S": "finapi"},
  "vendor_session_id": {"S": "$vsid"},
  "vendor_session_url": {"S": "$vurl"},
  "instant_payment": {"BOOL": $instant},
  "payment_tracking_enabled": {"BOOL": $tracking},
  "finalized": {"BOOL": $finalized},
  "webhook_received": {"BOOL": $wh},
  "callback_sent": {"BOOL": $cb_sent},
  "callback_delivered": {"BOOL": $cb_deliv},
  "created_at": {"N": "$created"},
  "updated_at": {"N": "$created"},
  "expires_at": {"N": "$expires"}$e2e_attr
}
JSON
  ddb put-item --table-name "$PAYMENTS_TABLE" --item file:///tmp/a2a-seed-item.json >/dev/null

  # ---- PR row for tracked payments (recon != none) ----
  if [ "$PR_AVAILABLE" = true ] && [ "$tracking" = "true" ] && [ "$recon" != "none" ]; then
    addl="\"purpose\": {\"S\": \"$(esc "$purpose")\"}, \"senderIban\": {\"S\": \"$siban\"}, \"instant\": {\"BOOL\": $instant}"
    [ -n "$e2e" ] && addl="$addl, \"endToEndId\": {\"S\": \"$(esc "$e2e")\"}"
    recon_extra=""
    if [ "$recon" = "Reconciled" ]; then
      bank_tx="65000$(printf '%05d' $((RANDOM % 100000)))"
      recon_extra=", \"reconciliation_date\": {\"N\": \"$created\"}, \"transaction_settlement_date\": {\"N\": \"$created\"}, \"reconciled\": {\"BOOL\": true}, \"match_metadata\": {\"M\": {\"matchedBankTxId\": {\"N\": \"$bank_tx\"}, \"matchedTier\": {\"S\": \"tier-instant\"}, \"matchedConfidence\": {\"S\": \"high\"}, \"matchedAt\": {\"N\": \"$created\"}}}"
    else
      recon_extra=", \"reconciled\": {\"BOOL\": false}"
    fi
    cat > /tmp/a2a-seed-pr.json <<JSON
{
  "mandate_id": {"S": "$CLIENT_ID#$tenant#$pid"},
  "sk": {"S": "TRANSACTION#$pid"},
  "transaction_id": {"S": "$pid"},
  "external_transaction_id": {"S": "$pid"},
  "source_reference": {"S": "$pid"},
  "client_id": {"S": "$CLIENT_ID"},
  "tenant_id": {"S": "$tenant"},
  "amount": {"N": "$amount"},
  "currency": {"S": "$currency"},
  "transaction_date": {"N": "$created"},
  "reconciliation_status": {"S": "$recon"},
  "product_source": {"S": "A2A"},
  "payment_reference": {"S": "$(esc "$corr")"},
  "payment_purpose": {"S": "$(esc "$purpose")"},
  "recipient_iban": {"S": "$riban"},
  "additional_information": {"M": {$addl}},
  "created_at": {"N": "$created"}$recon_extra
}
JSON
    ddb put-item --table-name "$PR_TABLE" --item file:///tmp/a2a-seed-pr.json >/dev/null

    # Base payment-transactions row the FE join reads. reconcilable_transaction_id = pid links
    # directly to the PR row above (orchestrator matches reconcilable.transaction_id first).
    if [ "$PT_AVAILABLE" = true ]; then
      pt_corr=""; [ -n "$corr" ] && pt_corr="\"correlation_id\": {\"S\": \"$(esc "$corr")\"},"
      cat > /tmp/a2a-seed-pt.json <<JSON
{
  "payment_id": {"S": "$pid"},
  "sk": {"S": "TRANSACTION#$pid"},
  "transaction_id": {"S": "$pid"},
  "client_id": {"S": "$CLIENT_ID"},
  "tenant_id": {"S": "$tenant"},
  "amount": {"N": "$amount"},
  "currency": {"S": "$currency"},
  "transaction_date": {"N": "$created"},
  $pt_corr
  "payment_reference": {"S": "$(esc "$corr")"},
  "payment_purpose": {"S": "$(esc "$purpose")"},
  "payment_tracking_enabled": {"BOOL": true},
  "reconcilable_transaction_id": {"S": "$pid"},
  "created_at": {"N": "$created"}
}
JSON
      ddb put-item --table-name "$PT_TABLE" --item file:///tmp/a2a-seed-pt.json >/dev/null
    fi

    print_info "  • $pid  $status  €$amount  track=$tracking  recon=$recon  (+PR+PT)"
  else
    print_info "  • $pid  $status  €$amount  track=$tracking  recon=$recon"
  fi
done

# ---------- match-conflict row (DEC-062) for the ambiguous 008/009 pair ----------
if [ "$CONFLICTS_AVAILABLE" = true ]; then
  C_AT="${T[2h]}"; W_FROM="${T[2h]}"; W_TO="$((${T[2h]} + 36*HOUR_MS))"
  CONFLICT_ID="seed-conflict-fox-207"
  # Idempotent
  ddb delete-item --table-name "$CONFLICTS_TABLE" --key "{\"conflict_id\":{\"S\":\"$CONFLICT_ID\"}}" >/dev/null 2>&1 || true
  # Build the over-complete conflict as plain JSON, then marshal to DynamoDB attribute-value JSON.
  CONFLICT_ID="$CONFLICT_ID" CLIENT_ID="$CLIENT_ID" IBAN_FAM="$IBAN_FAM" MERCHANT_FOX="$MERCHANT_FOX" \
  C_AT="$C_AT" W_FROM="$W_FROM" W_TO="$W_TO" TTL="$(( C_AT/1000 + 180*86400 ))" \
  python3 - <<'PY' > /tmp/a2a-seed-conflict.json
import os, json
e=os.environ
at=int(e['C_AT']); wf=int(e['W_FROM']); wt=int(e['W_TO']); cid=e['CLIENT_ID']; fam=e['IBAN_FAM']; fox=e['MERCHANT_FOX']
def pay(pid,sender,purpose):
    return {"paymentId":pid,"amount":2.07,"currency":"EUR","anchorAt":at,"recipientIban":fox,
            "senderIban":fam,"purpose":purpose,"instant":True,"resolved":False}
def credit(btx,name):
    return {"bankTransactionId":btx,"amount":2.07,"currency":"EUR","bookingDate":at,
            "purpose":"Reconciliation test 6","counterpartName":name,"senderIban":fam,"accountIban":fox}
def ev(pid,btx):
    return {"paymentId":pid,"bankTransactionId":btx,"amountMatch":True,"currencyMatch":True,"scheme":"instant",
            "windowFrom":wf,"windowTo":wt,"inWindow":True,"senderCompatible":True,"senderConfirmed":False,
            "purposeScore":0.5,"endToEndIdMatch":False,"transactionCodeInPurpose":False,
            "verdict":"amount+currency+sender+window all match, but two payments share the family IBAN and "
                      "neither credit carries an endToEndId or distinguishing purpose -> cannot safely assign"}
# NOTE: top-level keys are snake_case (the DynamoMatchConflictRecorder maps the domain object to these
# column names); nested payments/credits/evaluations keep their camelCase domain field names because the
# document client serialises those JS objects as-is.
conflict={
  "conflict_id":e['CONFLICT_ID'],"created_at":at,"connection_ref":cid+"#tenant-fox","client_id":cid,
  "tenant_id":"tenant-fox","reason":"ambiguous_same_amount_group","amount":2.07,"currency":"EUR",
  "payments":[pay("seed-a2a-008","Max P","Reconciliation test 6"),
              pay("seed-a2a-009","Sister P","Reconciliation test 6")],
  "credits":[credit("6500002071","Max P"),credit("6500002072","Sister P")],
  "evaluations":[ev("seed-a2a-008","6500002071"),ev("seed-a2a-008","6500002072"),
                 ev("seed-a2a-009","6500002071"),ev("seed-a2a-009","6500002072")],
  "summary":"Two A2A payments (seed-a2a-008, seed-a2a-009) of EUR 2.07 from the same family IBAN "
            +fam+" matched two indistinguishable EUR 2.07 instant credits within the 36h window. With no "
            "endToEndId, no transaction code, and identical purpose/sender, a 1:1 assignment cannot be made "
            "safely, so both were deferred for the next run / manual review.",
  "ttl":int(e['TTL']),
}
def marshal(v):
    if isinstance(v,bool): return {"BOOL":v}
    if isinstance(v,(int,float)): return {"N":str(v)}
    if isinstance(v,str): return {"S":v}
    if isinstance(v,list): return {"L":[marshal(x) for x in v]}
    if isinstance(v,dict): return {"M":{k:marshal(x) for k,x in v.items()}}
    raise TypeError(type(v))
print(json.dumps({k:marshal(x) for k,x in conflict.items()}))
PY
  ddb put-item --table-name "$CONFLICTS_TABLE" --item file:///tmp/a2a-seed-conflict.json >/dev/null
  print_info "  • match-conflict $CONFLICT_ID  (2 payments × 2 credits, ambiguous_same_amount_group)"
fi

rm -f /tmp/a2a-seed-item.json /tmp/a2a-seed-pr.json /tmp/a2a-seed-pt.json /tmp/a2a-seed-conflict.json
print_success "Seeded ${#ROWS[@]} A2A payments + PR rows + base tx rows + 1 match-conflict — 1:1 with live."
