#!/bin/bash

# =============================================================================
# Seed local DebitGuard data (transactions + verifications)
# =============================================================================
# Populates the two DynamoDB tables the FE DebitGuard / "Secure Direct Debits"
# page (pages/iban-check.vue) renders:
#   - calytics-be-local-transactions  (the report table)
#   - calytics-be-local-verifications (the metrics counters)
#
# Both be-admin endpoints (GET /clients/{id}/secure-direct-debits/report and
# /metrics) read these tables with a Scan filtered by `client_id`, so the only
# hard requirement for a row to render is client_id == the logged-in client.
#
# The fixtures (seeders/fixtures/dg-*.json) are byte-for-byte real row shapes
# captured from a working local environment, with the client id replaced by the
# __CLIENT_ID__ placeholder. We resolve the real main client id (a random uuid
# generated by be-admin's seed:clients since the CPM refactor) and substitute it
# in. Item PKs are stable (TRANSACTION#{id}), so re-running overwrites in place —
# no orphaned rows when the client id changes on a fresh re-seed.
#
# Usage:   cal seed dg-data
# Env:     AWS_ENDPOINT_URL, AWS_REGION, TRANSACTION_TABLE_NAME,
#          VERIFICATION_TABLE_NAME, POSTGRES_*, SEED_DG_CLIENT_ID,
#          SEED_DG_CLIENT_EMAIL
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FIXTURES_DIR="$SCRIPT_DIR/fixtures"

export AWS_ENDPOINT_URL="${AWS_ENDPOINT_URL:-http://localhost:4566}"
export AWS_REGION="${AWS_REGION:-eu-central-1}"
export AWS_PAGER=""

TRANSACTION_TABLE="${TRANSACTION_TABLE_NAME:-calytics-be-local-transactions}"
VERIFICATION_TABLE="${VERIFICATION_TABLE_NAME:-calytics-be-local-verifications}"

POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
POSTGRES_USER="${POSTGRES_USER:-postgres}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-register}"
POSTGRES_DB="${POSTGRES_DB:-calytics-admin}"
SEED_DG_CLIENT_EMAIL="${SEED_DG_CLIENT_EMAIL:-main.client@gmail.com}"
FALLBACK_CLIENT_ID="9f8a1f8c-56fd-43f9-b0dd-db0c86cf424a"

GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
print_info()    { echo -e "${CYAN}ℹ${NC}  $1"; }
print_success() { echo -e "${GREEN}✓${NC}  $1"; }
print_warn()    { echo -e "${YELLOW}!${NC}  $1"; }
print_error()   { echo -e "${RED}✗${NC}  $1"; }

ddb() { aws --endpoint-url "$AWS_ENDPOINT_URL" --region "$AWS_REGION" dynamodb "$@"; }

# Resolve the client these fixtures attach to. The FE filters by the logged-in
# client's id; resolve it from Postgres (the users -> user_clients join be-admin
# uses), honouring an explicit override, fall back to the historical fixture uuid.
resolve_dg_client_id() {
    command -v psql >/dev/null 2>&1 || return 0
    PGPASSWORD="$POSTGRES_PASSWORD" psql -h "$POSTGRES_HOST" -p "$POSTGRES_PORT" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -t -A -q \
        -c "SELECT uc.client_id FROM user_clients uc JOIN users u ON u.user_id = uc.user_id WHERE u.email = '$SEED_DG_CLIENT_EMAIL' LIMIT 1;" 2>/dev/null | grep -v '^$' | head -1 || true
}

if [ -n "${SEED_DG_CLIENT_ID:-}" ]; then
    CLIENT_ID="$SEED_DG_CLIENT_ID"
else
    CLIENT_ID="$(resolve_dg_client_id)"
    [ -z "$CLIENT_ID" ] && CLIENT_ID="$FALLBACK_CLIENT_ID"
fi
print_info "DebitGuard fixtures will attach to client: $CLIENT_ID"

# Guard: tables must exist (created by terraform/serverless sync, not this seeder)
ddb describe-table --table-name "$TRANSACTION_TABLE"  >/dev/null 2>&1 || { print_error "Table $TRANSACTION_TABLE not found — run 'cal sync terraform' / deploy first."; exit 1; }
ddb describe-table --table-name "$VERIFICATION_TABLE" >/dev/null 2>&1 || { print_error "Table $VERIFICATION_TABLE not found — run 'cal sync terraform' / deploy first."; exit 1; }

# Seed one fixture file (array of DynamoDB attribute-value items) into a table.
# Substitutes the __CLIENT_ID__ placeholder, then batch-writes in chunks of 25.
seed_fixture() {
    sf_file="$1"; sf_table="$2"
    [ -f "$sf_file" ] || { print_warn "Fixture $sf_file missing — skipping $sf_table"; return 0; }

    sf_count=$(CLIENT_ID="$CLIENT_ID" SF_TABLE="$sf_table" node -e '
        const fs = require("fs");
        const file = process.argv[1];
        const table = process.env.SF_TABLE;
        const clientId = process.env.CLIENT_ID;
        const items = JSON.parse(fs.readFileSync(file, "utf8").split("__CLIENT_ID__").join(clientId));
        // DynamoDB batch-write allows max 25 PutRequests per call.
        const chunks = [];
        for (let i = 0; i < items.length; i += 25) chunks.push(items.slice(i, i + 25));
        chunks.forEach((chunk, idx) => {
            const payload = { [table]: chunk.map(Item => ({ PutRequest: { Item } })) };
            fs.writeFileSync(`/tmp/dg-batch-${table}-${idx}.json`, JSON.stringify(payload));
        });
        process.stdout.write(String(items.length));
    ' "$sf_file")

    for batch in /tmp/dg-batch-"$sf_table"-*.json; do
        [ -f "$batch" ] || continue
        ddb batch-write-item --request-items "file://$batch" >/dev/null
        rm -f "$batch"
    done
    print_success "Seeded $sf_count rows into $sf_table"
}

print_info "Seeding DebitGuard transactions + verifications"
seed_fixture "$FIXTURES_DIR/dg-transactions.json"  "$TRANSACTION_TABLE"
seed_fixture "$FIXTURES_DIR/dg-verifications.json" "$VERIFICATION_TABLE"

# Verification
TX_COUNT=$(ddb scan --table-name "$TRANSACTION_TABLE"  --filter-expression "client_id = :c" --expression-attribute-values "{\":c\":{\"S\":\"$CLIENT_ID\"}}" --select COUNT --query 'Count' --output text 2>/dev/null)
VF_COUNT=$(ddb scan --table-name "$VERIFICATION_TABLE" --filter-expression "client_id = :c" --expression-attribute-values "{\":c\":{\"S\":\"$CLIENT_ID\"}}" --select COUNT --query 'Count' --output text 2>/dev/null)
print_success "DebitGuard seed complete — client $CLIENT_ID now has $TX_COUNT transactions, $VF_COUNT verifications"
